version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
        - main_network
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    build: .
    env_file: ./.env
    command: sh -c 'npm run migrate:up && npm start'
    environment:
      - MYSQL_HOST=mysqldb
    ports:
      - "$APPLICATION_PORT:$APPLICATION_PORT"
    expose:
      - $APPLICATION_PORT
    volumes:
      - uploads:/app/uploads
    networks:
        - main_network
    
networks:
  main_network:
    driver: bridge

volumes:
  mysqldb:
    driver: local
  uploads:
    driver: local